openapi: 3.0.3
info:
  title: Laravel API Platform - Auth API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: API Gateway local dev
paths:
  /auth/login:
    post:
      summary: Login and receive a JWT
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            examples:
              default:
                value:
                  email: test@example.com
                  password: password
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                invalid:
                  value:
                    code: invalid_credentials
                    message: Invalid email or password
        "422":
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        "429":
          description: Too many login attempts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                throttle:
                  value:
                    code: too_many_requests
                    message: Too many login attempts
components:
  schemas:
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 3
    TokenResponse:
      type: object
      properties:
        token:
          type: string
        token_type:
          type: string
          example: Bearer
        expires_in:
          type: integer
          example: 900
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    ValidationError:
      type: object
      properties:
        code:
          type: string
          example: validation_error
        message:
          type: string
          example: Validation failed
        details:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
