openapi: 3.0.3
info:
  title: Laravel API Platform - Tasks API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: API Gateway local dev
security:
  - bearerAuth: []
paths:
  /tasks:
    get:
      summary: List tasks
      operationId: listTasks
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: [pending, done]
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          default: 1
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
          default: 10
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  page:
                    type: integer
                  limit:
                    type: integer
                  total:
                    type: integer
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
    post:
      summary: Create task
      operationId: createTask
      parameters:
        - in: header
          name: Idempotency-Key
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateRequest'
      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        "400":
          description: Missing Idempotency-Key
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "409":
          description: Idempotency conflict
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "422":
          description: Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Task:
      type: object
      properties:
        id: { type: string, format: uuid }
        title: { type: string }
        status:
          type: string
          enum: [pending, done]
        created_at:
          type: string
          format: date-time
    TaskCreateRequest:
      type: object
      required: [title]
      properties:
        title:
          type: string
          maxLength: 255
        status:
          type: string
          enum: [pending, done]
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    ValidationError:
      type: object
      properties:
        code:
          type: string
          example: validation_error
        message:
          type: string
          example: Validation failed
        details:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
